/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountImportanceListDTO,
  AccountMetaDataDTO,
  AccountMetaDataPairDTO,
  HarvestInfoListDTO,
  KeyPairDTO,
  MosaicDefinitionListDTO,
  MosaicListDTO,
  NamespaceListDTO,
  TransactionListDTO,
  UnconfirmedTransactionListDTO,
} from '../models/index';
import {
    AccountImportanceListDTOFromJSON,
    AccountImportanceListDTOToJSON,
    AccountMetaDataDTOFromJSON,
    AccountMetaDataDTOToJSON,
    AccountMetaDataPairDTOFromJSON,
    AccountMetaDataPairDTOToJSON,
    HarvestInfoListDTOFromJSON,
    HarvestInfoListDTOToJSON,
    KeyPairDTOFromJSON,
    KeyPairDTOToJSON,
    MosaicDefinitionListDTOFromJSON,
    MosaicDefinitionListDTOToJSON,
    MosaicListDTOFromJSON,
    MosaicListDTOToJSON,
    NamespaceListDTOFromJSON,
    NamespaceListDTOToJSON,
    TransactionListDTOFromJSON,
    TransactionListDTOToJSON,
    UnconfirmedTransactionListDTOFromJSON,
    UnconfirmedTransactionListDTOToJSON,
} from '../models/index';

export interface AccountGetForwardedFromPublicKeyGetRequest {
    publicKey?: string;
}

export interface AccountGetForwardedGetRequest {
    address?: string;
}

export interface AccountGetFromPublicKeyGetRequest {
    publicKey?: string;
}

export interface AccountGetGetRequest {
    address?: string;
}

export interface AccountHarvestsGetRequest {
    address?: string;
    hash?: string;
}

export interface AccountHistoricalGetGetRequest {
    address?: string;
    startHeight?: number;
    endHeight?: number;
    increment?: number;
}

export interface AccountLockPostRequest {
    privateKey?: string;
}

export interface AccountMosaicDefinitionPageGetRequest {
    address?: string;
    parent?: string;
}

export interface AccountMosaicOwnedGetRequest {
    address?: string;
}

export interface AccountNamespacePageGetRequest {
    address?: string;
    parent?: string;
}

export interface AccountStatusGetRequest {
    address?: string;
}

export interface AccountTransfersAllGetRequest {
    address?: string;
}

export interface AccountTransfersIncomingGetRequest {
    address?: string;
}

export interface AccountTransfersOutgoingGetRequest {
    address?: string;
}

export interface AccountUnconfirmedTransactionsGetRequest {
    address?: string;
}

export interface AccountUnlockPostRequest {
    privateKey?: string;
}

/**
 * 
 */
export class AccountApi extends runtime.BaseAPI {

    /**
     * Requesting the original account data for a delegate account (Public key)
     */
    async accountGetForwardedFromPublicKeyGetRaw(requestParameters: AccountGetForwardedFromPublicKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountMetaDataPairDTO>> {
        const queryParameters: any = {};

        if (requestParameters['publicKey'] != null) {
            queryParameters['publicKey'] = requestParameters['publicKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/get/forwarded/from-public-key`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountMetaDataPairDTOFromJSON(jsonValue));
    }

    /**
     * Requesting the original account data for a delegate account (Public key)
     */
    async accountGetForwardedFromPublicKeyGet(requestParameters: AccountGetForwardedFromPublicKeyGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountMetaDataPairDTO> {
        const response = await this.accountGetForwardedFromPublicKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Requesting the original account data for a delegate account
     */
    async accountGetForwardedGetRaw(requestParameters: AccountGetForwardedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountMetaDataPairDTO>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/get/forwarded`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountMetaDataPairDTOFromJSON(jsonValue));
    }

    /**
     * Requesting the original account data for a delegate account
     */
    async accountGetForwardedGet(requestParameters: AccountGetForwardedGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountMetaDataPairDTO> {
        const response = await this.accountGetForwardedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Requesting the account data (public key)
     */
    async accountGetFromPublicKeyGetRaw(requestParameters: AccountGetFromPublicKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountMetaDataPairDTO>> {
        const queryParameters: any = {};

        if (requestParameters['publicKey'] != null) {
            queryParameters['publicKey'] = requestParameters['publicKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/get/from-public-key`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountMetaDataPairDTOFromJSON(jsonValue));
    }

    /**
     * Requesting the account data (public key)
     */
    async accountGetFromPublicKeyGet(requestParameters: AccountGetFromPublicKeyGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountMetaDataPairDTO> {
        const response = await this.accountGetFromPublicKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Requesting the account data
     */
    async accountGetGetRaw(requestParameters: AccountGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountMetaDataPairDTO>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountMetaDataPairDTOFromJSON(jsonValue));
    }

    /**
     * Requesting the account data
     */
    async accountGetGet(requestParameters: AccountGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountMetaDataPairDTO> {
        const response = await this.accountGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Requesting harvest info data for an account
     */
    async accountHarvestsGetRaw(requestParameters: AccountHarvestsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HarvestInfoListDTO>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['hash'] != null) {
            queryParameters['hash'] = requestParameters['hash'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/harvests`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HarvestInfoListDTOFromJSON(jsonValue));
    }

    /**
     * Requesting harvest info data for an account
     */
    async accountHarvestsGet(requestParameters: AccountHarvestsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HarvestInfoListDTO> {
        const response = await this.accountHarvestsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieving historical account data
     */
    async accountHistoricalGetGetRaw(requestParameters: AccountHistoricalGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['startHeight'] != null) {
            queryParameters['startHeight'] = requestParameters['startHeight'];
        }

        if (requestParameters['endHeight'] != null) {
            queryParameters['endHeight'] = requestParameters['endHeight'];
        }

        if (requestParameters['increment'] != null) {
            queryParameters['increment'] = requestParameters['increment'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/historical/get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Retrieving historical account data
     */
    async accountHistoricalGetGet(requestParameters: AccountHistoricalGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.accountHistoricalGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieving account importances for accounts
     */
    async accountImportancesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountImportanceListDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/importances`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountImportanceListDTOFromJSON(jsonValue));
    }

    /**
     * Retrieving account importances for accounts
     */
    async accountImportancesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountImportanceListDTO> {
        const response = await this.accountImportancesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Locking the account (stops harvesting)
     */
    async accountLockPostRaw(requestParameters: AccountLockPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['privateKey'] != null) {
            formParams.append('privateKey', requestParameters['privateKey'] as any);
        }


        let urlPath = `/account/lock`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Locking the account (stops harvesting)
     */
    async accountLockPost(requestParameters: AccountLockPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.accountLockPostRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieving mosaic definitions that an account has created
     */
    async accountMosaicDefinitionPageGetRaw(requestParameters: AccountMosaicDefinitionPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MosaicDefinitionListDTO>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['parent'] != null) {
            queryParameters['parent'] = requestParameters['parent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/mosaic/definition/page`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MosaicDefinitionListDTOFromJSON(jsonValue));
    }

    /**
     * Retrieving mosaic definitions that an account has created
     */
    async accountMosaicDefinitionPageGet(requestParameters: AccountMosaicDefinitionPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MosaicDefinitionListDTO> {
        const response = await this.accountMosaicDefinitionPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieving mosaics that an account owns
     */
    async accountMosaicOwnedGetRaw(requestParameters: AccountMosaicOwnedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MosaicListDTO>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/mosaic/owned`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MosaicListDTOFromJSON(jsonValue));
    }

    /**
     * Retrieving mosaics that an account owns
     */
    async accountMosaicOwnedGet(requestParameters: AccountMosaicOwnedGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MosaicListDTO> {
        const response = await this.accountMosaicOwnedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieving namespaces that an account owns
     */
    async accountNamespacePageGetRaw(requestParameters: AccountNamespacePageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NamespaceListDTO>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['parent'] != null) {
            queryParameters['parent'] = requestParameters['parent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/namespace/page`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NamespaceListDTOFromJSON(jsonValue));
    }

    /**
     * Retrieving namespaces that an account owns
     */
    async accountNamespacePageGet(requestParameters: AccountNamespacePageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NamespaceListDTO> {
        const response = await this.accountNamespacePageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Requesting the account status
     */
    async accountStatusGetRaw(requestParameters: AccountStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountMetaDataDTO>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/status`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountMetaDataDTOFromJSON(jsonValue));
    }

    /**
     * Requesting the account status
     */
    async accountStatusGet(requestParameters: AccountStatusGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountMetaDataDTO> {
        const response = await this.accountStatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Requesting transaction data for an account (All)
     */
    async accountTransfersAllGetRaw(requestParameters: AccountTransfersAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionListDTO>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/transfers/all`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionListDTOFromJSON(jsonValue));
    }

    /**
     * Requesting transaction data for an account (All)
     */
    async accountTransfersAllGet(requestParameters: AccountTransfersAllGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionListDTO> {
        const response = await this.accountTransfersAllGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Requesting transaction data for an account (Incoming)
     */
    async accountTransfersIncomingGetRaw(requestParameters: AccountTransfersIncomingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionListDTO>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/transfers/incoming`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionListDTOFromJSON(jsonValue));
    }

    /**
     * Requesting transaction data for an account (Incoming)
     */
    async accountTransfersIncomingGet(requestParameters: AccountTransfersIncomingGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionListDTO> {
        const response = await this.accountTransfersIncomingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Requesting transaction data for an account (Outgoing)
     */
    async accountTransfersOutgoingGetRaw(requestParameters: AccountTransfersOutgoingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionListDTO>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/transfers/outgoing`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionListDTOFromJSON(jsonValue));
    }

    /**
     * Requesting transaction data for an account (Outgoing)
     */
    async accountTransfersOutgoingGet(requestParameters: AccountTransfersOutgoingGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionListDTO> {
        const response = await this.accountTransfersOutgoingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unconfirmed transactions
     */
    async accountUnconfirmedTransactionsGetRaw(requestParameters: AccountUnconfirmedTransactionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UnconfirmedTransactionListDTO>> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/unconfirmedTransactions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UnconfirmedTransactionListDTOFromJSON(jsonValue));
    }

    /**
     * Unconfirmed transactions
     */
    async accountUnconfirmedTransactionsGet(requestParameters: AccountUnconfirmedTransactionsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UnconfirmedTransactionListDTO> {
        const response = await this.accountUnconfirmedTransactionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unlocking the account (enables harvesting)
     */
    async accountUnlockPostRaw(requestParameters: AccountUnlockPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['privateKey'] != null) {
            formParams.append('privateKey', requestParameters['privateKey'] as any);
        }


        let urlPath = `/account/unlock`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Unlocking the account (enables harvesting)
     */
    async accountUnlockPost(requestParameters: AccountUnlockPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.accountUnlockPostRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieving the unlock info
     */
    async accountUnlockedInfoPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/unlocked/info`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieving the unlock info
     */
    async accountUnlockedInfoPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.accountUnlockedInfoPostRaw(initOverrides);
    }

    /**
     * Generates a KeyPairViewModel.
     * Retrieving account data
     */
    async generateRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyPairDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/generate`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeyPairDTOFromJSON(jsonValue));
    }

    /**
     * Generates a KeyPairViewModel.
     * Retrieving account data
     */
    async generate(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyPairDTO> {
        const response = await this.generateRaw(initOverrides);
        return await response.value();
    }

}
