/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BlockDTO,
} from '../models/index';
import {
    BlockDTOFromJSON,
    BlockDTOToJSON,
} from '../models/index';

export interface BlockAtPublicPostRequest {
    blockHeight?: string;
}

export interface BlockGetGetRequest {
    blockHash?: string;
}

/**
 * 
 */
export class BlockApi extends runtime.BaseAPI {

    /**
     * Getting a block with a given height
     */
    async blockAtPublicPostRaw(requestParameters: BlockAtPublicPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['blockHeight'] != null) {
            formParams.append('blockHeight ', requestParameters['blockHeight'] as any);
        }


        let urlPath = `/block/at/public`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Getting a block with a given height
     */
    async blockAtPublicPost(requestParameters: BlockAtPublicPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.blockAtPublicPostRaw(requestParameters, initOverrides);
    }

    /**
     * Getting a block with a given hash
     */
    async blockGetGetRaw(requestParameters: BlockGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlockDTO>> {
        const queryParameters: any = {};

        if (requestParameters['blockHash'] != null) {
            queryParameters['blockHash'] = requestParameters['blockHash'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/block/get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockDTOFromJSON(jsonValue));
    }

    /**
     * Getting a block with a given hash
     */
    async blockGetGet(requestParameters: BlockGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlockDTO> {
        const response = await this.blockGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
