/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BlockChainScoreDTO,
  BlockDTO,
  BlockHeightDTO,
} from '../models/index';
import {
    BlockChainScoreDTOFromJSON,
    BlockChainScoreDTOToJSON,
    BlockDTOFromJSON,
    BlockDTOToJSON,
    BlockHeightDTOFromJSON,
    BlockHeightDTOToJSON,
} from '../models/index';

/**
 * 
 */
export class ChainApi extends runtime.BaseAPI {

    /**
     * Block chain height
     */
    async chainHeightGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlockHeightDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chain/height`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockHeightDTOFromJSON(jsonValue));
    }

    /**
     * Block chain height
     */
    async chainHeightGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlockHeightDTO> {
        const response = await this.chainHeightGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Last block of the block chain score
     */
    async chainLastBlockGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlockDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chain/last-block`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockDTOFromJSON(jsonValue));
    }

    /**
     * Last block of the block chain score
     */
    async chainLastBlockGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlockDTO> {
        const response = await this.chainLastBlockGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Block chain score
     */
    async chainScoreGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlockChainScoreDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chain/score`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockChainScoreDTOFromJSON(jsonValue));
    }

    /**
     * Block chain score
     */
    async chainScoreGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlockChainScoreDTO> {
        const response = await this.chainScoreGetRaw(initOverrides);
        return await response.value();
    }

}
