/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TimeSynchronizationListDTO,
} from '../models/index';
import {
    TimeSynchronizationListDTOFromJSON,
    TimeSynchronizationListDTOToJSON,
} from '../models/index';

/**
 * 
 */
export class DebugApi extends runtime.BaseAPI {

    /**
     * Monitoring incoming calls
     */
    async debugConnectionsIncomingGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/debug/connections/incoming`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Monitoring incoming calls
     */
    async debugConnectionsIncomingGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.debugConnectionsIncomingGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Monitoring outgoing calls
     */
    async debugConnectionsOutgoingGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/debug/connections/outgoing`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Monitoring outgoing calls
     */
    async debugConnectionsOutgoingGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.debugConnectionsOutgoingGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Monitoring the network time
     */
    async debugTimeSynchronizationGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSynchronizationListDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/debug/time-synchronization`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSynchronizationListDTOFromJSON(jsonValue));
    }

    /**
     * Monitoring the network time
     */
    async debugTimeSynchronizationGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSynchronizationListDTO> {
        const response = await this.debugTimeSynchronizationGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Monitoring timers
     */
    async debugTimersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/debug/timers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Monitoring timers
     */
    async debugTimersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.debugTimersGetRaw(initOverrides);
        return await response.value();
    }

}
