/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HeartbeatDTO,
} from '../models/index';
import {
    HeartbeatDTOFromJSON,
    HeartbeatDTOToJSON,
} from '../models/index';

/**
 * 
 */
export class HeartbeatApi extends runtime.BaseAPI {

    /**
     * Determines if NIS is up and responsive.
     * Heart beat
     */
    async getHeartbeatRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HeartbeatDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/heartbeat`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HeartbeatDTOFromJSON(jsonValue));
    }

    /**
     * Determines if NIS is up and responsive.
     * Heart beat
     */
    async getHeartbeat(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HeartbeatDTO> {
        const response = await this.getHeartbeatRaw(initOverrides);
        return await response.value();
    }

}
