/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface LocalAccountTransfersAllPostRequest {
    page?: string;
}

export interface LocalAccountTransfersIncomingPostRequest {
    page?: string;
}

export interface LocalAccountTransfersOutgoingPostRequest {
    page?: string;
}

export interface LocalChainBlocksAfterPostRequest {
    blockHeight?: string;
}

/**
 * 
 */
export class LocalApi extends runtime.BaseAPI {

    /**
     * All transactions with decoded messages
     */
    async localAccountTransfersAllPostRaw(requestParameters: LocalAccountTransfersAllPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['page'] != null) {
            formParams.append('page', requestParameters['page'] as any);
        }


        let urlPath = `/local/account/transfers/all`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * All transactions with decoded messages
     */
    async localAccountTransfersAllPost(requestParameters: LocalAccountTransfersAllPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.localAccountTransfersAllPostRaw(requestParameters, initOverrides);
    }

    /**
     * Incoming transactions with decoded messages
     */
    async localAccountTransfersIncomingPostRaw(requestParameters: LocalAccountTransfersIncomingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['page'] != null) {
            formParams.append('page', requestParameters['page'] as any);
        }


        let urlPath = `/local/account/transfers/incoming`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Incoming transactions with decoded messages
     */
    async localAccountTransfersIncomingPost(requestParameters: LocalAccountTransfersIncomingPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.localAccountTransfersIncomingPostRaw(requestParameters, initOverrides);
    }

    /**
     * Outgoing transactions with decoded messages
     */
    async localAccountTransfersOutgoingPostRaw(requestParameters: LocalAccountTransfersOutgoingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['page'] != null) {
            formParams.append('page', requestParameters['page'] as any);
        }


        let urlPath = `/local/account/transfers/outgoing`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Outgoing transactions with decoded messages
     */
    async localAccountTransfersOutgoingPost(requestParameters: LocalAccountTransfersOutgoingPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.localAccountTransfersOutgoingPostRaw(requestParameters, initOverrides);
    }

    /**
     * Getting part of a chain
     */
    async localChainBlocksAfterPostRaw(requestParameters: LocalChainBlocksAfterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['blockHeight'] != null) {
            formParams.append('blockHeight', requestParameters['blockHeight'] as any);
        }


        let urlPath = `/local/chain/blocks-after`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Getting part of a chain
     */
    async localChainBlocksAfterPost(requestParameters: LocalChainBlocksAfterPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.localChainBlocksAfterPostRaw(requestParameters, initOverrides);
    }

}
