/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MosaicDefinitionListDTO,
  NamespaceListDTO,
} from '../models/index';
import {
    MosaicDefinitionListDTOFromJSON,
    MosaicDefinitionListDTOToJSON,
    NamespaceListDTOFromJSON,
    NamespaceListDTOToJSON,
} from '../models/index';

export interface NamespaceGetRequest {
    namespace?: string;
}

export interface NamespaceMosaicDefinitionPageGetRequest {
    namespace?: string;
}

export interface NamespaceRootsGetRequest {
    id?: number;
    pageSize?: number;
}

/**
 * 
 */
export class NamespaceApi extends runtime.BaseAPI {

    /**
     * Retrieving a specific namespace
     */
    async namespaceGetRaw(requestParameters: NamespaceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/namespace`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Retrieving a specific namespace
     */
    async namespaceGet(requestParameters: NamespaceGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.namespaceGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieving mosaic definitions
     */
    async namespaceMosaicDefinitionPageGetRaw(requestParameters: NamespaceMosaicDefinitionPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MosaicDefinitionListDTO>> {
        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/namespace/mosaic/definition/page`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MosaicDefinitionListDTOFromJSON(jsonValue));
    }

    /**
     * Retrieving mosaic definitions
     */
    async namespaceMosaicDefinitionPageGet(requestParameters: NamespaceMosaicDefinitionPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MosaicDefinitionListDTO> {
        const response = await this.namespaceMosaicDefinitionPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieving root namespaces
     */
    async namespaceRootsGetRaw(requestParameters: NamespaceRootsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NamespaceListDTO>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize;'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/namespace/roots`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NamespaceListDTOFromJSON(jsonValue));
    }

    /**
     * Retrieving root namespaces
     */
    async namespaceRootsGet(requestParameters: NamespaceRootsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NamespaceListDTO> {
        const response = await this.namespaceRootsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
