/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BlockHeightDTO,
  ExtendedNodeInfoDTO,
  NodeDTO,
  NodeListDTO,
} from '../models/index';
import {
    BlockHeightDTOFromJSON,
    BlockHeightDTOToJSON,
    ExtendedNodeInfoDTOFromJSON,
    ExtendedNodeInfoDTOToJSON,
    NodeDTOFromJSON,
    NodeDTOToJSON,
    NodeListDTOFromJSON,
    NodeListDTOToJSON,
} from '../models/index';

export interface NodeBootPostRequest {
    bootNodeRequest?: string;
}

/**
 * 
 */
export class NodeApi extends runtime.BaseAPI {

    /**
     * Maximum chain height in the active neighborhood
     */
    async nodeActivePeersMaxChainHeightGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlockHeightDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/node/active-peers/max-chain-height`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockHeightDTOFromJSON(jsonValue));
    }

    /**
     * Maximum chain height in the active neighborhood
     */
    async nodeActivePeersMaxChainHeightGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlockHeightDTO> {
        const response = await this.nodeActivePeersMaxChainHeightGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Booting the local node
     */
    async nodeBootPostRaw(requestParameters: NodeBootPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['bootNodeRequest'] != null) {
            formParams.append('bootNodeRequest', requestParameters['bootNodeRequest'] as any);
        }


        let urlPath = `/node/boot`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Booting the local node
     */
    async nodeBootPost(requestParameters: NodeBootPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.nodeBootPostRaw(requestParameters, initOverrides);
    }

    /**
     * Requesting node experiences
     */
    async nodeExperiencesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/node/experiences`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Requesting node experiences
     */
    async nodeExperiencesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.nodeExperiencesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Extended node information
     */
    async nodeExtendedInfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExtendedNodeInfoDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/node/extended-info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExtendedNodeInfoDTOFromJSON(jsonValue));
    }

    /**
     * Extended node information
     */
    async nodeExtendedInfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExtendedNodeInfoDTO> {
        const response = await this.nodeExtendedInfoGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Basic node information
     */
    async nodeInfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodeDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/node/info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeDTOFromJSON(jsonValue));
    }

    /**
     * Basic node information
     */
    async nodeInfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodeDTO> {
        const response = await this.nodeInfoGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Active neighborhood
     */
    async nodePeerListActiveGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodeListDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/node/peer-list/active`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeListDTOFromJSON(jsonValue));
    }

    /**
     * Active neighborhood
     */
    async nodePeerListActiveGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodeListDTO> {
        const response = await this.nodePeerListActiveGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Complete neighborhood
     */
    async nodePeerListAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodeListDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/node/peer-list/all`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeListDTOFromJSON(jsonValue));
    }

    /**
     * Complete neighborhood
     */
    async nodePeerListAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodeListDTO> {
        const response = await this.nodePeerListAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Reachable neighborhood
     */
    async nodePeerListReachableGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodeListDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/node/peer-list/reachable`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeListDTOFromJSON(jsonValue));
    }

    /**
     * Reachable neighborhood
     */
    async nodePeerListReachableGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodeListDTO> {
        const response = await this.nodePeerListReachableGetRaw(initOverrides);
        return await response.value();
    }

}
