/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface TransactionAnnouncePostRequest {
    requestAnnounce?: string;
}

export interface TransactionPrepareAnnouncePostRequest {
    requestPrepareAnnounce?: string;
}

/**
 * 
 */
export class TransactionApi extends runtime.BaseAPI {

    /**
     * Sending the data to NIS
     */
    async transactionAnnouncePostRaw(requestParameters: TransactionAnnouncePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['requestAnnounce'] != null) {
            formParams.append('requestAnnounce', requestParameters['requestAnnounce'] as any);
        }


        let urlPath = `/transaction/announce`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Sending the data to NIS
     */
    async transactionAnnouncePost(requestParameters: TransactionAnnouncePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transactionAnnouncePostRaw(requestParameters, initOverrides);
    }

    /**
     * Initiating a transaction
     */
    async transactionPrepareAnnouncePostRaw(requestParameters: TransactionPrepareAnnouncePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['requestPrepareAnnounce'] != null) {
            formParams.append('requestPrepareAnnounce', requestParameters['requestPrepareAnnounce'] as any);
        }


        let urlPath = `/transaction/prepare-announce`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Initiating a transaction
     */
    async transactionPrepareAnnouncePost(requestParameters: TransactionPrepareAnnouncePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transactionPrepareAnnouncePostRaw(requestParameters, initOverrides);
    }

}
