/* tslint:disable */
/* eslint-disable */
/**
 * Copyright © 2025 The Symbol Syndicate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CosignatureDTO
 */
export interface CosignatureDTO {
    /**
     * Entity's signature generated by the signer.
     * @type {string}
     * @memberof CosignatureDTO
     */
    signature: string;
    /**
     * Cosignature version.
     * @type {string}
     * @memberof CosignatureDTO
     */
    version: string;
    /**
     * Public key.
     * @type {string}
     * @memberof CosignatureDTO
     */
    signerPublicKey: string;
}

/**
 * Check if a given object implements the CosignatureDTO interface.
 */
export function instanceOfCosignatureDTO(value: object): value is CosignatureDTO {
    if (!('signature' in value) || value['signature'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('signerPublicKey' in value) || value['signerPublicKey'] === undefined) return false;
    return true;
}

export function CosignatureDTOFromJSON(json: any): CosignatureDTO {
    return CosignatureDTOFromJSONTyped(json, false);
}

export function CosignatureDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CosignatureDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'signature': json['signature'],
        'version': json['version'],
        'signerPublicKey': json['signerPublicKey'],
    };
}

export function CosignatureDTOToJSON(json: any): CosignatureDTO {
    return CosignatureDTOToJSONTyped(json, false);
}

export function CosignatureDTOToJSONTyped(value?: CosignatureDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signature': value['signature'],
        'version': value['version'],
        'signerPublicKey': value['signerPublicKey'],
    };
}

