import { readdir, writeFile } from 'fs/promises';
import { extname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const srcDir = join(__dirname, '../src');

// 指定ディレクトリにindex.jsを生成
async function writeBarrel(dir, relPrefix = './') {
  const files = (await readdir(dir, { withFileTypes: true }))
    .filter((e) => e.isFile() && extname(e.name) === '.js' && e.name !== 'index.js')
    .map((e) => `export * from '${relPrefix}${e.name}';`);
  if (files.length > 0) {
    await writeFile(join(dir, 'index.js'), '// Auto-generated by generate-index.js\n' + files.join('\n') + '\n');
    console.log(`index.js generated in ${dir}`);
  }
}

// src直下
await writeBarrel(srcDir);
// symbolディレクトリ
await writeBarrel(join(srcDir, 'symbol'), './');
