/* tslint:disable */
/* eslint-disable */
/**
 * Copyright © 2025 The Symbol Syndicate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { mapValues } from '../runtime.js';
import type { AliasActionEnum } from './AliasActionEnum.js';
import {
  AliasActionEnumFromJSON,
  AliasActionEnumFromJSONTyped,
  AliasActionEnumToJSON,
  AliasActionEnumToJSONTyped,
} from './AliasActionEnum.js';
import type { NetworkTypeEnum } from './NetworkTypeEnum.js';
import {
  NetworkTypeEnumFromJSON,
  NetworkTypeEnumFromJSONTyped,
  NetworkTypeEnumToJSON,
  NetworkTypeEnumToJSONTyped,
} from './NetworkTypeEnum.js';

/**
 * Transaction to link a namespace to an account.
 * @export
 * @interface AddressAliasTransactionDTO
 */
export interface AddressAliasTransactionDTO {
  /**
   * A number that allows uint 32 values.
   * @type {number}
   * @memberof AddressAliasTransactionDTO
   */
  size: number;
  /**
   * Entity's signature generated by the signer.
   * @type {string}
   * @memberof AddressAliasTransactionDTO
   */
  signature: string;
  /**
   * Public key.
   * @type {string}
   * @memberof AddressAliasTransactionDTO
   */
  signerPublicKey: string;
  /**
   * Entity version.
   * @type {number}
   * @memberof AddressAliasTransactionDTO
   */
  version: number;
  /**
   *
   * @type {NetworkTypeEnum}
   * @memberof AddressAliasTransactionDTO
   */
  network: NetworkTypeEnum;
  /**
   *
   * @type {number}
   * @memberof AddressAliasTransactionDTO
   */
  type: number;
  /**
   * Absolute amount. An amount of 123456789 (absolute) for a mosaic with divisibility 6 means 123.456789 (relative).
   * @type {string}
   * @memberof AddressAliasTransactionDTO
   */
  maxFee: string;
  /**
   * Duration expressed in number of blocks.
   * @type {string}
   * @memberof AddressAliasTransactionDTO
   */
  deadline: string;
  /**
   * Namespace identifier.
   * @type {string}
   * @memberof AddressAliasTransactionDTO
   */
  namespaceId: string;
  /**
   * Address encoded using a 32-character set.
   * @type {string}
   * @memberof AddressAliasTransactionDTO
   */
  address: string;
  /**
   *
   * @type {AliasActionEnum}
   * @memberof AddressAliasTransactionDTO
   */
  aliasAction: AliasActionEnum;
}

/**
 * Check if a given object implements the AddressAliasTransactionDTO interface.
 */
export function instanceOfAddressAliasTransactionDTO(value: object): value is AddressAliasTransactionDTO {
  if (!('size' in value) || value['size'] === undefined) return false;
  if (!('signature' in value) || value['signature'] === undefined) return false;
  if (!('signerPublicKey' in value) || value['signerPublicKey'] === undefined) return false;
  if (!('version' in value) || value['version'] === undefined) return false;
  if (!('network' in value) || value['network'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('maxFee' in value) || value['maxFee'] === undefined) return false;
  if (!('deadline' in value) || value['deadline'] === undefined) return false;
  if (!('namespaceId' in value) || value['namespaceId'] === undefined) return false;
  if (!('address' in value) || value['address'] === undefined) return false;
  if (!('aliasAction' in value) || value['aliasAction'] === undefined) return false;
  return true;
}

export function AddressAliasTransactionDTOFromJSON(json: any): AddressAliasTransactionDTO {
  return AddressAliasTransactionDTOFromJSONTyped(json, false);
}

export function AddressAliasTransactionDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AddressAliasTransactionDTO {
  if (json == null) {
    return json;
  }
  return {
    size: json['size'],
    signature: json['signature'],
    signerPublicKey: json['signerPublicKey'],
    version: json['version'],
    network: NetworkTypeEnumFromJSON(json['network']),
    type: json['type'],
    maxFee: json['maxFee'],
    deadline: json['deadline'],
    namespaceId: json['namespaceId'],
    address: json['address'],
    aliasAction: AliasActionEnumFromJSON(json['aliasAction']),
  };
}

export function AddressAliasTransactionDTOToJSON(json: any): AddressAliasTransactionDTO {
  return AddressAliasTransactionDTOToJSONTyped(json, false);
}

export function AddressAliasTransactionDTOToJSONTyped(
  value?: AddressAliasTransactionDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    size: value['size'],
    signature: value['signature'],
    signerPublicKey: value['signerPublicKey'],
    version: value['version'],
    network: NetworkTypeEnumToJSON(value['network']),
    type: value['type'],
    maxFee: value['maxFee'],
    deadline: value['deadline'],
    namespaceId: value['namespaceId'],
    address: value['address'],
    aliasAction: AliasActionEnumToJSON(value['aliasAction']),
  };
}
