/* tslint:disable */
/* eslint-disable */
/**
 * Copyright © 2025 The Symbol Syndicate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { mapValues } from '../runtime.js';

/**
 *
 * @export
 * @interface Cosignature
 */
export interface Cosignature {
  /**
   *
   * @type {string}
   * @memberof Cosignature
   */
  parentHash?: string;
  /**
   * Entity's signature generated by the signer.
   * @type {string}
   * @memberof Cosignature
   */
  signature?: string;
  /**
   * Public key.
   * @type {string}
   * @memberof Cosignature
   */
  signerPublicKey?: string;
  /**
   * Cosignature version.
   * @type {string}
   * @memberof Cosignature
   */
  version?: string;
}

/**
 * Check if a given object implements the Cosignature interface.
 */
export function instanceOfCosignature(value: object): value is Cosignature {
  return true;
}

export function CosignatureFromJSON(json: any): Cosignature {
  return CosignatureFromJSONTyped(json, false);
}

export function CosignatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cosignature {
  if (json == null) {
    return json;
  }
  return {
    parentHash: json['parentHash'] == null ? undefined : json['parentHash'],
    signature: json['signature'] == null ? undefined : json['signature'],
    signerPublicKey: json['signerPublicKey'] == null ? undefined : json['signerPublicKey'],
    version: json['version'] == null ? undefined : json['version'],
  };
}

export function CosignatureToJSON(json: any): Cosignature {
  return CosignatureToJSONTyped(json, false);
}

export function CosignatureToJSONTyped(value?: Cosignature | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    parentHash: value['parentHash'],
    signature: value['signature'],
    signerPublicKey: value['signerPublicKey'],
    version: value['version'],
  };
}
