/* tslint:disable */
/* eslint-disable */
/**
 * Copyright © 2025 The Symbol Syndicate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { mapValues } from '../runtime.js';
import type { MosaicSupplyChangeActionEnum } from './MosaicSupplyChangeActionEnum.js';
import {
  MosaicSupplyChangeActionEnumFromJSON,
  MosaicSupplyChangeActionEnumFromJSONTyped,
  MosaicSupplyChangeActionEnumToJSON,
  MosaicSupplyChangeActionEnumToJSONTyped,
} from './MosaicSupplyChangeActionEnum.js';
import type { NetworkTypeEnum } from './NetworkTypeEnum.js';
import {
  NetworkTypeEnumFromJSON,
  NetworkTypeEnumFromJSONTyped,
  NetworkTypeEnumToJSON,
  NetworkTypeEnumToJSONTyped,
} from './NetworkTypeEnum.js';

/**
 * Transaction to increase or decrease the supply of a mosaic.
 * @export
 * @interface MosaicSupplyChangeTransactionDTO
 */
export interface MosaicSupplyChangeTransactionDTO {
  /**
   * A number that allows uint 32 values.
   * @type {number}
   * @memberof MosaicSupplyChangeTransactionDTO
   */
  size: number;
  /**
   * Entity's signature generated by the signer.
   * @type {string}
   * @memberof MosaicSupplyChangeTransactionDTO
   */
  signature: string;
  /**
   * Public key.
   * @type {string}
   * @memberof MosaicSupplyChangeTransactionDTO
   */
  signerPublicKey: string;
  /**
   * Entity version.
   * @type {number}
   * @memberof MosaicSupplyChangeTransactionDTO
   */
  version: number;
  /**
   *
   * @type {NetworkTypeEnum}
   * @memberof MosaicSupplyChangeTransactionDTO
   */
  network: NetworkTypeEnum;
  /**
   *
   * @type {number}
   * @memberof MosaicSupplyChangeTransactionDTO
   */
  type: number;
  /**
   * Absolute amount. An amount of 123456789 (absolute) for a mosaic with divisibility 6 means 123.456789 (relative).
   * @type {string}
   * @memberof MosaicSupplyChangeTransactionDTO
   */
  maxFee: string;
  /**
   * Duration expressed in number of blocks.
   * @type {string}
   * @memberof MosaicSupplyChangeTransactionDTO
   */
  deadline: string;
  /**
   * Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias)
   * is used instead of the real mosaic identifier.
   *
   * @type {string}
   * @memberof MosaicSupplyChangeTransactionDTO
   */
  mosaicId: string;
  /**
   * Absolute amount. An amount of 123456789 (absolute) for a mosaic with divisibility 6 means 123.456789 (relative).
   * @type {string}
   * @memberof MosaicSupplyChangeTransactionDTO
   */
  delta: string;
  /**
   *
   * @type {MosaicSupplyChangeActionEnum}
   * @memberof MosaicSupplyChangeTransactionDTO
   */
  action: MosaicSupplyChangeActionEnum;
}

/**
 * Check if a given object implements the MosaicSupplyChangeTransactionDTO interface.
 */
export function instanceOfMosaicSupplyChangeTransactionDTO(value: object): value is MosaicSupplyChangeTransactionDTO {
  if (!('size' in value) || value['size'] === undefined) return false;
  if (!('signature' in value) || value['signature'] === undefined) return false;
  if (!('signerPublicKey' in value) || value['signerPublicKey'] === undefined) return false;
  if (!('version' in value) || value['version'] === undefined) return false;
  if (!('network' in value) || value['network'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('maxFee' in value) || value['maxFee'] === undefined) return false;
  if (!('deadline' in value) || value['deadline'] === undefined) return false;
  if (!('mosaicId' in value) || value['mosaicId'] === undefined) return false;
  if (!('delta' in value) || value['delta'] === undefined) return false;
  if (!('action' in value) || value['action'] === undefined) return false;
  return true;
}

export function MosaicSupplyChangeTransactionDTOFromJSON(json: any): MosaicSupplyChangeTransactionDTO {
  return MosaicSupplyChangeTransactionDTOFromJSONTyped(json, false);
}

export function MosaicSupplyChangeTransactionDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MosaicSupplyChangeTransactionDTO {
  if (json == null) {
    return json;
  }
  return {
    size: json['size'],
    signature: json['signature'],
    signerPublicKey: json['signerPublicKey'],
    version: json['version'],
    network: NetworkTypeEnumFromJSON(json['network']),
    type: json['type'],
    maxFee: json['maxFee'],
    deadline: json['deadline'],
    mosaicId: json['mosaicId'],
    delta: json['delta'],
    action: MosaicSupplyChangeActionEnumFromJSON(json['action']),
  };
}

export function MosaicSupplyChangeTransactionDTOToJSON(json: any): MosaicSupplyChangeTransactionDTO {
  return MosaicSupplyChangeTransactionDTOToJSONTyped(json, false);
}

export function MosaicSupplyChangeTransactionDTOToJSONTyped(
  value?: MosaicSupplyChangeTransactionDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    size: value['size'],
    signature: value['signature'],
    signerPublicKey: value['signerPublicKey'],
    version: value['version'],
    network: NetworkTypeEnumToJSON(value['network']),
    type: value['type'],
    maxFee: value['maxFee'],
    deadline: value['deadline'],
    mosaicId: value['mosaicId'],
    delta: value['delta'],
    action: MosaicSupplyChangeActionEnumToJSON(value['action']),
  };
}
