/* tslint:disable */
/* eslint-disable */
/**
 * Copyright © 2025 The Symbol Syndicate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { mapValues } from '../runtime.js';

/**
 *
 * @export
 * @interface ParentPublicKeySignaturePair
 */
export interface ParentPublicKeySignaturePair {
  /**
   * Public key.
   * @type {string}
   * @memberof ParentPublicKeySignaturePair
   */
  parentPublicKey: string;
  /**
   * Entity's signature generated by the signer.
   * @type {string}
   * @memberof ParentPublicKeySignaturePair
   */
  signature: string;
}

/**
 * Check if a given object implements the ParentPublicKeySignaturePair interface.
 */
export function instanceOfParentPublicKeySignaturePair(value: object): value is ParentPublicKeySignaturePair {
  if (!('parentPublicKey' in value) || value['parentPublicKey'] === undefined) return false;
  if (!('signature' in value) || value['signature'] === undefined) return false;
  return true;
}

export function ParentPublicKeySignaturePairFromJSON(json: any): ParentPublicKeySignaturePair {
  return ParentPublicKeySignaturePairFromJSONTyped(json, false);
}

export function ParentPublicKeySignaturePairFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ParentPublicKeySignaturePair {
  if (json == null) {
    return json;
  }
  return {
    parentPublicKey: json['parentPublicKey'],
    signature: json['signature'],
  };
}

export function ParentPublicKeySignaturePairToJSON(json: any): ParentPublicKeySignaturePair {
  return ParentPublicKeySignaturePairToJSONTyped(json, false);
}

export function ParentPublicKeySignaturePairToJSONTyped(
  value?: ParentPublicKeySignaturePair | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    parentPublicKey: value['parentPublicKey'],
    signature: value['signature'],
  };
}
