/* tslint:disable */
/* eslint-disable */
/**
 * Copyright © 2025 The Symbol Syndicate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { mapValues } from '../runtime.js';

/**
 *
 * @export
 * @interface VerifiableEntityDTO
 */
export interface VerifiableEntityDTO {
  /**
   * Entity's signature generated by the signer.
   * @type {string}
   * @memberof VerifiableEntityDTO
   */
  signature: string;
}

/**
 * Check if a given object implements the VerifiableEntityDTO interface.
 */
export function instanceOfVerifiableEntityDTO(value: object): value is VerifiableEntityDTO {
  if (!('signature' in value) || value['signature'] === undefined) return false;
  return true;
}

export function VerifiableEntityDTOFromJSON(json: any): VerifiableEntityDTO {
  return VerifiableEntityDTOFromJSONTyped(json, false);
}

export function VerifiableEntityDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifiableEntityDTO {
  if (json == null) {
    return json;
  }
  return {
    signature: json['signature'],
  };
}

export function VerifiableEntityDTOToJSON(json: any): VerifiableEntityDTO {
  return VerifiableEntityDTOToJSONTyped(json, false);
}

export function VerifiableEntityDTOToJSONTyped(
  value?: VerifiableEntityDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    signature: value['signature'],
  };
}
