/* tslint:disable */
/* eslint-disable */
/**
 * Copyright © 2025 The Symbol Syndicate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { mapValues } from '../runtime.js';
import type { LinkActionEnum } from './LinkActionEnum.js';
import {
  LinkActionEnumFromJSON,
  LinkActionEnumFromJSONTyped,
  LinkActionEnumToJSON,
  LinkActionEnumToJSONTyped,
} from './LinkActionEnum.js';
import type { NetworkTypeEnum } from './NetworkTypeEnum.js';
import {
  NetworkTypeEnumFromJSON,
  NetworkTypeEnumFromJSONTyped,
  NetworkTypeEnumToJSON,
  NetworkTypeEnumToJSONTyped,
} from './NetworkTypeEnum.js';

/**
 * Transaction to link an account with a VRF public key.
 * The key is used to randomize block production and leader/participant selection.
 * Required for all harvesting eligible accounts.
 *
 * @export
 * @interface VrfKeyLinkTransactionDTO
 */
export interface VrfKeyLinkTransactionDTO {
  /**
   * A number that allows uint 32 values.
   * @type {number}
   * @memberof VrfKeyLinkTransactionDTO
   */
  size: number;
  /**
   * Entity's signature generated by the signer.
   * @type {string}
   * @memberof VrfKeyLinkTransactionDTO
   */
  signature: string;
  /**
   * Public key.
   * @type {string}
   * @memberof VrfKeyLinkTransactionDTO
   */
  signerPublicKey: string;
  /**
   * Entity version.
   * @type {number}
   * @memberof VrfKeyLinkTransactionDTO
   */
  version: number;
  /**
   *
   * @type {NetworkTypeEnum}
   * @memberof VrfKeyLinkTransactionDTO
   */
  network: NetworkTypeEnum;
  /**
   *
   * @type {number}
   * @memberof VrfKeyLinkTransactionDTO
   */
  type: number;
  /**
   * Absolute amount. An amount of 123456789 (absolute) for a mosaic with divisibility 6 means 123.456789 (relative).
   * @type {string}
   * @memberof VrfKeyLinkTransactionDTO
   */
  maxFee: string;
  /**
   * Duration expressed in number of blocks.
   * @type {string}
   * @memberof VrfKeyLinkTransactionDTO
   */
  deadline: string;
  /**
   * Public key.
   * @type {string}
   * @memberof VrfKeyLinkTransactionDTO
   */
  linkedPublicKey: string;
  /**
   *
   * @type {LinkActionEnum}
   * @memberof VrfKeyLinkTransactionDTO
   */
  linkAction: LinkActionEnum;
}

/**
 * Check if a given object implements the VrfKeyLinkTransactionDTO interface.
 */
export function instanceOfVrfKeyLinkTransactionDTO(value: object): value is VrfKeyLinkTransactionDTO {
  if (!('size' in value) || value['size'] === undefined) return false;
  if (!('signature' in value) || value['signature'] === undefined) return false;
  if (!('signerPublicKey' in value) || value['signerPublicKey'] === undefined) return false;
  if (!('version' in value) || value['version'] === undefined) return false;
  if (!('network' in value) || value['network'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('maxFee' in value) || value['maxFee'] === undefined) return false;
  if (!('deadline' in value) || value['deadline'] === undefined) return false;
  if (!('linkedPublicKey' in value) || value['linkedPublicKey'] === undefined) return false;
  if (!('linkAction' in value) || value['linkAction'] === undefined) return false;
  return true;
}

export function VrfKeyLinkTransactionDTOFromJSON(json: any): VrfKeyLinkTransactionDTO {
  return VrfKeyLinkTransactionDTOFromJSONTyped(json, false);
}

export function VrfKeyLinkTransactionDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VrfKeyLinkTransactionDTO {
  if (json == null) {
    return json;
  }
  return {
    size: json['size'],
    signature: json['signature'],
    signerPublicKey: json['signerPublicKey'],
    version: json['version'],
    network: NetworkTypeEnumFromJSON(json['network']),
    type: json['type'],
    maxFee: json['maxFee'],
    deadline: json['deadline'],
    linkedPublicKey: json['linkedPublicKey'],
    linkAction: LinkActionEnumFromJSON(json['linkAction']),
  };
}

export function VrfKeyLinkTransactionDTOToJSON(json: any): VrfKeyLinkTransactionDTO {
  return VrfKeyLinkTransactionDTOToJSONTyped(json, false);
}

export function VrfKeyLinkTransactionDTOToJSONTyped(
  value?: VrfKeyLinkTransactionDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    size: value['size'],
    signature: value['signature'],
    signerPublicKey: value['signerPublicKey'],
    version: value['version'],
    network: NetworkTypeEnumToJSON(value['network']),
    type: value['type'],
    maxFee: value['maxFee'],
    deadline: value['deadline'],
    linkedPublicKey: value['linkedPublicKey'],
    linkAction: LinkActionEnumToJSON(value['linkAction']),
  };
}
