/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountImportanceDTO } from './AccountImportanceDTO';
import {
    AccountImportanceDTOFromJSON,
    AccountImportanceDTOFromJSONTyped,
    AccountImportanceDTOToJSON,
    AccountImportanceDTOToJSONTyped,
} from './AccountImportanceDTO';

/**
 * 
 * @export
 * @interface AccountImportanceListDTO
 */
export interface AccountImportanceListDTO {
    /**
     * Array of account importance data
     * @type {Array<AccountImportanceDTO>}
     * @memberof AccountImportanceListDTO
     */
    data?: Array<AccountImportanceDTO>;
}

/**
 * Check if a given object implements the AccountImportanceListDTO interface.
 */
export function instanceOfAccountImportanceListDTO(value: object): value is AccountImportanceListDTO {
    return true;
}

export function AccountImportanceListDTOFromJSON(json: any): AccountImportanceListDTO {
    return AccountImportanceListDTOFromJSONTyped(json, false);
}

export function AccountImportanceListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountImportanceListDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AccountImportanceDTOFromJSON)),
    };
}

export function AccountImportanceListDTOToJSON(json: any): AccountImportanceListDTO {
    return AccountImportanceListDTOToJSONTyped(json, false);
}

export function AccountImportanceListDTOToJSONTyped(value?: AccountImportanceListDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AccountImportanceDTOToJSON)),
    };
}

