/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountMetaDataDTO
 */
export interface AccountMetaDataDTO {
    /**
     * Array of cosignatory account addresses
     * @type {Array<string>}
     * @memberof AccountMetaDataDTO
     */
    cosignatories?: Array<string>;
    /**
     * Array of accounts this account is a cosignatory of
     * @type {Array<string>}
     * @memberof AccountMetaDataDTO
     */
    cosignatoryOf?: Array<string>;
    /**
     * Account status (LOCKED/UNLOCKED)
     * @type {string}
     * @memberof AccountMetaDataDTO
     */
    status?: string;
    /**
     * Remote harvesting status (INACTIVE/ACTIVE)
     * @type {string}
     * @memberof AccountMetaDataDTO
     */
    remoteStatus?: string;
}

/**
 * Check if a given object implements the AccountMetaDataDTO interface.
 */
export function instanceOfAccountMetaDataDTO(value: object): value is AccountMetaDataDTO {
    return true;
}

export function AccountMetaDataDTOFromJSON(json: any): AccountMetaDataDTO {
    return AccountMetaDataDTOFromJSONTyped(json, false);
}

export function AccountMetaDataDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountMetaDataDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'cosignatories': json['cosignatories'] == null ? undefined : json['cosignatories'],
        'cosignatoryOf': json['cosignatoryOf'] == null ? undefined : json['cosignatoryOf'],
        'status': json['status'] == null ? undefined : json['status'],
        'remoteStatus': json['remoteStatus'] == null ? undefined : json['remoteStatus'],
    };
}

export function AccountMetaDataDTOToJSON(json: any): AccountMetaDataDTO {
    return AccountMetaDataDTOToJSONTyped(json, false);
}

export function AccountMetaDataDTOToJSONTyped(value?: AccountMetaDataDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cosignatories': value['cosignatories'],
        'cosignatoryOf': value['cosignatoryOf'],
        'status': value['status'],
        'remoteStatus': value['remoteStatus'],
    };
}

