/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountDTO
 */
export interface AccountDTO {
    /**
     * The address of the account
     * @type {string}
     * @memberof AccountDTO
     */
    address?: string;
    /**
     * Number of blocks harvested by this account
     * @type {number}
     * @memberof AccountDTO
     */
    harvestedBlocks?: number;
    /**
     * Account balance in micro XEM
     * @type {number}
     * @memberof AccountDTO
     */
    balance?: number;
    /**
     * Importance of the account
     * @type {number}
     * @memberof AccountDTO
     */
    importance?: number;
    /**
     * Vested balance in micro XEM
     * @type {number}
     * @memberof AccountDTO
     */
    vestedBalance?: number;
    /**
     * Public key of the account
     * @type {string}
     * @memberof AccountDTO
     */
    publicKey?: string;
    /**
     * Label of the account
     * @type {string}
     * @memberof AccountDTO
     */
    label?: string | null;
    /**
     * Multisig information
     * @type {object}
     * @memberof AccountDTO
     */
    multisigInfo?: object;
}

/**
 * Check if a given object implements the AccountDTO interface.
 */
export function instanceOfAccountDTO(value: object): value is AccountDTO {
    return true;
}

export function AccountDTOFromJSON(json: any): AccountDTO {
    return AccountDTOFromJSONTyped(json, false);
}

export function AccountDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'harvestedBlocks': json['harvestedBlocks'] == null ? undefined : json['harvestedBlocks'],
        'balance': json['balance'] == null ? undefined : json['balance'],
        'importance': json['importance'] == null ? undefined : json['importance'],
        'vestedBalance': json['vestedBalance'] == null ? undefined : json['vestedBalance'],
        'publicKey': json['publicKey'] == null ? undefined : json['publicKey'],
        'label': json['label'] == null ? undefined : json['label'],
        'multisigInfo': json['multisigInfo'] == null ? undefined : json['multisigInfo'],
    };
}

export function AccountDTOToJSON(json: any): AccountDTO {
    return AccountDTOToJSONTyped(json, false);
}

export function AccountDTOToJSONTyped(value?: AccountDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'harvestedBlocks': value['harvestedBlocks'],
        'balance': value['balance'],
        'importance': value['importance'],
        'vestedBalance': value['vestedBalance'],
        'publicKey': value['publicKey'],
        'label': value['label'],
        'multisigInfo': value['multisigInfo'],
    };
}

