/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImportanceDTO } from './ImportanceDTO';
import {
    ImportanceDTOFromJSON,
    ImportanceDTOFromJSONTyped,
    ImportanceDTOToJSON,
    ImportanceDTOToJSONTyped,
} from './ImportanceDTO';

/**
 * 
 * @export
 * @interface AccountImportanceDTO
 */
export interface AccountImportanceDTO {
    /**
     * Account address
     * @type {string}
     * @memberof AccountImportanceDTO
     */
    address?: string;
    /**
     * 
     * @type {ImportanceDTO}
     * @memberof AccountImportanceDTO
     */
    importance?: ImportanceDTO;
}

/**
 * Check if a given object implements the AccountImportanceDTO interface.
 */
export function instanceOfAccountImportanceDTO(value: object): value is AccountImportanceDTO {
    return true;
}

export function AccountImportanceDTOFromJSON(json: any): AccountImportanceDTO {
    return AccountImportanceDTOFromJSONTyped(json, false);
}

export function AccountImportanceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountImportanceDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'importance': json['importance'] == null ? undefined : ImportanceDTOFromJSON(json['importance']),
    };
}

export function AccountImportanceDTOToJSON(json: any): AccountImportanceDTO {
    return AccountImportanceDTOToJSONTyped(json, false);
}

export function AccountImportanceDTOToJSONTyped(value?: AccountImportanceDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'importance': ImportanceDTOToJSON(value['importance']),
    };
}

