/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountMetaDataDTO } from './AccountMetaDataDTO';
import {
    AccountMetaDataDTOFromJSON,
    AccountMetaDataDTOFromJSONTyped,
    AccountMetaDataDTOToJSON,
    AccountMetaDataDTOToJSONTyped,
} from './AccountMetaDataDTO';
import type { AccountDTO } from './AccountDTO';
import {
    AccountDTOFromJSON,
    AccountDTOFromJSONTyped,
    AccountDTOToJSON,
    AccountDTOToJSONTyped,
} from './AccountDTO';

/**
 * 
 * @export
 * @interface AccountMetaDataPairDTO
 */
export interface AccountMetaDataPairDTO {
    /**
     * 
     * @type {AccountMetaDataDTO}
     * @memberof AccountMetaDataPairDTO
     */
    meta?: AccountMetaDataDTO;
    /**
     * 
     * @type {AccountDTO}
     * @memberof AccountMetaDataPairDTO
     */
    account?: AccountDTO;
}

/**
 * Check if a given object implements the AccountMetaDataPairDTO interface.
 */
export function instanceOfAccountMetaDataPairDTO(value: object): value is AccountMetaDataPairDTO {
    return true;
}

export function AccountMetaDataPairDTOFromJSON(json: any): AccountMetaDataPairDTO {
    return AccountMetaDataPairDTOFromJSONTyped(json, false);
}

export function AccountMetaDataPairDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountMetaDataPairDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : AccountMetaDataDTOFromJSON(json['meta']),
        'account': json['account'] == null ? undefined : AccountDTOFromJSON(json['account']),
    };
}

export function AccountMetaDataPairDTOToJSON(json: any): AccountMetaDataPairDTO {
    return AccountMetaDataPairDTOToJSONTyped(json, false);
}

export function AccountMetaDataPairDTOToJSONTyped(value?: AccountMetaDataPairDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': AccountMetaDataDTOToJSON(value['meta']),
        'account': AccountDTOToJSON(value['account']),
    };
}

