/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HashDTO } from './HashDTO';
import {
    HashDTOFromJSON,
    HashDTOFromJSONTyped,
    HashDTOToJSON,
    HashDTOToJSONTyped,
} from './HashDTO';

/**
 * 
 * @export
 * @interface BlockDTO
 */
export interface BlockDTO {
    /**
     * Block timestamp
     * @type {number}
     * @memberof BlockDTO
     */
    timeStamp?: number;
    /**
     * Block signature
     * @type {string}
     * @memberof BlockDTO
     */
    signature?: string;
    /**
     * 
     * @type {HashDTO}
     * @memberof BlockDTO
     */
    prevBlockHash?: HashDTO;
    /**
     * Block type
     * @type {number}
     * @memberof BlockDTO
     */
    type?: number;
    /**
     * Array of transactions in the block
     * @type {Array<object>}
     * @memberof BlockDTO
     */
    transactions?: Array<object>;
    /**
     * Block version
     * @type {number}
     * @memberof BlockDTO
     */
    version?: number;
    /**
     * Public key of the block signer
     * @type {string}
     * @memberof BlockDTO
     */
    signer?: string;
    /**
     * Block height
     * @type {number}
     * @memberof BlockDTO
     */
    height?: number;
}

/**
 * Check if a given object implements the BlockDTO interface.
 */
export function instanceOfBlockDTO(value: object): value is BlockDTO {
    return true;
}

export function BlockDTOFromJSON(json: any): BlockDTO {
    return BlockDTOFromJSONTyped(json, false);
}

export function BlockDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'timeStamp': json['timeStamp'] == null ? undefined : json['timeStamp'],
        'signature': json['signature'] == null ? undefined : json['signature'],
        'prevBlockHash': json['prevBlockHash'] == null ? undefined : HashDTOFromJSON(json['prevBlockHash']),
        'type': json['type'] == null ? undefined : json['type'],
        'transactions': json['transactions'] == null ? undefined : json['transactions'],
        'version': json['version'] == null ? undefined : json['version'],
        'signer': json['signer'] == null ? undefined : json['signer'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function BlockDTOToJSON(json: any): BlockDTO {
    return BlockDTOToJSONTyped(json, false);
}

export function BlockDTOToJSONTyped(value?: BlockDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeStamp': value['timeStamp'],
        'signature': value['signature'],
        'prevBlockHash': HashDTOToJSON(value['prevBlockHash']),
        'type': value['type'],
        'transactions': value['transactions'],
        'version': value['version'],
        'signer': value['signer'],
        'height': value['height'],
    };
}

