/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockHeightDTO
 */
export interface BlockHeightDTO {
    /**
     * The current height of the blockchain
     * @type {number}
     * @memberof BlockHeightDTO
     */
    height?: number;
}

/**
 * Check if a given object implements the BlockHeightDTO interface.
 */
export function instanceOfBlockHeightDTO(value: object): value is BlockHeightDTO {
    return true;
}

export function BlockHeightDTOFromJSON(json: any): BlockHeightDTO {
    return BlockHeightDTOFromJSONTyped(json, false);
}

export function BlockHeightDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockHeightDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function BlockHeightDTOToJSON(json: any): BlockHeightDTO {
    return BlockHeightDTOToJSONTyped(json, false);
}

export function BlockHeightDTOToJSONTyped(value?: BlockHeightDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'height': value['height'],
    };
}

