/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockChainScoreDTO
 */
export interface BlockChainScoreDTO {
    /**
     * The blockchain score as a hexadecimal string
     * @type {string}
     * @memberof BlockChainScoreDTO
     */
    score?: string;
}

/**
 * Check if a given object implements the BlockChainScoreDTO interface.
 */
export function instanceOfBlockChainScoreDTO(value: object): value is BlockChainScoreDTO {
    return true;
}

export function BlockChainScoreDTOFromJSON(json: any): BlockChainScoreDTO {
    return BlockChainScoreDTOFromJSONTyped(json, false);
}

export function BlockChainScoreDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockChainScoreDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : json['score'],
    };
}

export function BlockChainScoreDTOToJSON(json: any): BlockChainScoreDTO {
    return BlockChainScoreDTOToJSONTyped(json, false);
}

export function BlockChainScoreDTOToJSONTyped(value?: BlockChainScoreDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
    };
}

