/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EndpointDTO
 */
export interface EndpointDTO {
    /**
     * Protocol (http/https)
     * @type {string}
     * @memberof EndpointDTO
     */
    protocol?: string;
    /**
     * Port number
     * @type {number}
     * @memberof EndpointDTO
     */
    port?: number;
    /**
     * Host name
     * @type {string}
     * @memberof EndpointDTO
     */
    host?: string;
}

/**
 * Check if a given object implements the EndpointDTO interface.
 */
export function instanceOfEndpointDTO(value: object): value is EndpointDTO {
    return true;
}

export function EndpointDTOFromJSON(json: any): EndpointDTO {
    return EndpointDTOFromJSONTyped(json, false);
}

export function EndpointDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndpointDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'protocol': json['protocol'] == null ? undefined : json['protocol'],
        'port': json['port'] == null ? undefined : json['port'],
        'host': json['host'] == null ? undefined : json['host'],
    };
}

export function EndpointDTOToJSON(json: any): EndpointDTO {
    return EndpointDTOToJSONTyped(json, false);
}

export function EndpointDTOToJSONTyped(value?: EndpointDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'protocol': value['protocol'],
        'port': value['port'],
        'host': value['host'],
    };
}

