/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NisInfoDTO } from './NisInfoDTO';
import {
    NisInfoDTOFromJSON,
    NisInfoDTOFromJSONTyped,
    NisInfoDTOToJSON,
    NisInfoDTOToJSONTyped,
} from './NisInfoDTO';
import type { NodeDTO } from './NodeDTO';
import {
    NodeDTOFromJSON,
    NodeDTOFromJSONTyped,
    NodeDTOToJSON,
    NodeDTOToJSONTyped,
} from './NodeDTO';

/**
 * 
 * @export
 * @interface ExtendedNodeInfoDTO
 */
export interface ExtendedNodeInfoDTO {
    /**
     * 
     * @type {NodeDTO}
     * @memberof ExtendedNodeInfoDTO
     */
    node?: NodeDTO;
    /**
     * 
     * @type {NisInfoDTO}
     * @memberof ExtendedNodeInfoDTO
     */
    nisInfo?: NisInfoDTO;
}

/**
 * Check if a given object implements the ExtendedNodeInfoDTO interface.
 */
export function instanceOfExtendedNodeInfoDTO(value: object): value is ExtendedNodeInfoDTO {
    return true;
}

export function ExtendedNodeInfoDTOFromJSON(json: any): ExtendedNodeInfoDTO {
    return ExtendedNodeInfoDTOFromJSONTyped(json, false);
}

export function ExtendedNodeInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtendedNodeInfoDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'node': json['node'] == null ? undefined : NodeDTOFromJSON(json['node']),
        'nisInfo': json['nisInfo'] == null ? undefined : NisInfoDTOFromJSON(json['nisInfo']),
    };
}

export function ExtendedNodeInfoDTOToJSON(json: any): ExtendedNodeInfoDTO {
    return ExtendedNodeInfoDTOToJSONTyped(json, false);
}

export function ExtendedNodeInfoDTOToJSONTyped(value?: ExtendedNodeInfoDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'node': NodeDTOToJSON(value['node']),
        'nisInfo': NisInfoDTOToJSON(value['nisInfo']),
    };
}

