/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HarvestInfoListDTO
 */
export interface HarvestInfoListDTO {
    /**
     * Array of harvest information
     * @type {Array<object>}
     * @memberof HarvestInfoListDTO
     */
    data?: Array<object>;
}

/**
 * Check if a given object implements the HarvestInfoListDTO interface.
 */
export function instanceOfHarvestInfoListDTO(value: object): value is HarvestInfoListDTO {
    return true;
}

export function HarvestInfoListDTOFromJSON(json: any): HarvestInfoListDTO {
    return HarvestInfoListDTOFromJSONTyped(json, false);
}

export function HarvestInfoListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): HarvestInfoListDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function HarvestInfoListDTOToJSON(json: any): HarvestInfoListDTO {
    return HarvestInfoListDTOToJSONTyped(json, false);
}

export function HarvestInfoListDTOToJSONTyped(value?: HarvestInfoListDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

