/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HashDTO
 */
export interface HashDTO {
    /**
     * Hash data as a hexadecimal string
     * @type {string}
     * @memberof HashDTO
     */
    data?: string;
}

/**
 * Check if a given object implements the HashDTO interface.
 */
export function instanceOfHashDTO(value: object): value is HashDTO {
    return true;
}

export function HashDTOFromJSON(json: any): HashDTO {
    return HashDTOFromJSONTyped(json, false);
}

export function HashDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function HashDTOToJSON(json: any): HashDTO {
    return HashDTOToJSONTyped(json, false);
}

export function HashDTOToJSONTyped(value?: HashDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

