/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdentityDTO
 */
export interface IdentityDTO {
    /**
     * Node name
     * @type {string}
     * @memberof IdentityDTO
     */
    name?: string;
    /**
     * Node public key
     * @type {string}
     * @memberof IdentityDTO
     */
    publicKey?: string;
}

/**
 * Check if a given object implements the IdentityDTO interface.
 */
export function instanceOfIdentityDTO(value: object): value is IdentityDTO {
    return true;
}

export function IdentityDTOFromJSON(json: any): IdentityDTO {
    return IdentityDTOFromJSONTyped(json, false);
}

export function IdentityDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'publicKey': json['public-key'] == null ? undefined : json['public-key'],
    };
}

export function IdentityDTOToJSON(json: any): IdentityDTO {
    return IdentityDTOToJSONTyped(json, false);
}

export function IdentityDTOToJSONTyped(value?: IdentityDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'public-key': value['publicKey'],
    };
}

