/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportanceDTO
 */
export interface ImportanceDTO {
    /**
     * Whether importance is set (0 or 1)
     * @type {number}
     * @memberof ImportanceDTO
     */
    isSet?: number;
    /**
     * Importance score
     * @type {number}
     * @memberof ImportanceDTO
     */
    score?: number;
    /**
     * Expected value
     * @type {number}
     * @memberof ImportanceDTO
     */
    ev?: number;
    /**
     * Block height when importance was calculated
     * @type {number}
     * @memberof ImportanceDTO
     */
    height?: number;
}

/**
 * Check if a given object implements the ImportanceDTO interface.
 */
export function instanceOfImportanceDTO(value: object): value is ImportanceDTO {
    return true;
}

export function ImportanceDTOFromJSON(json: any): ImportanceDTO {
    return ImportanceDTOFromJSONTyped(json, false);
}

export function ImportanceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportanceDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'isSet': json['isSet'] == null ? undefined : json['isSet'],
        'score': json['score'] == null ? undefined : json['score'],
        'ev': json['ev'] == null ? undefined : json['ev'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function ImportanceDTOToJSON(json: any): ImportanceDTO {
    return ImportanceDTOToJSONTyped(json, false);
}

export function ImportanceDTOToJSONTyped(value?: ImportanceDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isSet': value['isSet'],
        'score': value['score'],
        'ev': value['ev'],
        'height': value['height'],
    };
}

