/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeyPairDTO
 */
export interface KeyPairDTO {
    /**
     * The private key as hex string.
     * @type {string}
     * @memberof KeyPairDTO
     */
    privateKey?: string;
    /**
     * The address of the account.
     * @type {string}
     * @memberof KeyPairDTO
     */
    address?: string;
    /**
     * The public key as hex string.
     * @type {string}
     * @memberof KeyPairDTO
     */
    publicKey?: string;
}

/**
 * Check if a given object implements the KeyPairDTO interface.
 */
export function instanceOfKeyPairDTO(value: object): value is KeyPairDTO {
    return true;
}

export function KeyPairDTOFromJSON(json: any): KeyPairDTO {
    return KeyPairDTOFromJSONTyped(json, false);
}

export function KeyPairDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyPairDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'privateKey': json['privateKey'] == null ? undefined : json['privateKey'],
        'address': json['address'] == null ? undefined : json['address'],
        'publicKey': json['publicKey'] == null ? undefined : json['publicKey'],
    };
}

export function KeyPairDTOToJSON(json: any): KeyPairDTO {
    return KeyPairDTOToJSONTyped(json, false);
}

export function KeyPairDTOToJSONTyped(value?: KeyPairDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'privateKey': value['privateKey'],
        'address': value['address'],
        'publicKey': value['publicKey'],
    };
}

