/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageDTO
 */
export interface MessageDTO {
    /**
     * Message payload (hex encoded)
     * @type {string}
     * @memberof MessageDTO
     */
    payload?: string;
    /**
     * Message type (1 for plain, 2 for encrypted)
     * @type {number}
     * @memberof MessageDTO
     */
    type?: number;
}

/**
 * Check if a given object implements the MessageDTO interface.
 */
export function instanceOfMessageDTO(value: object): value is MessageDTO {
    return true;
}

export function MessageDTOFromJSON(json: any): MessageDTO {
    return MessageDTOFromJSONTyped(json, false);
}

export function MessageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'payload': json['payload'] == null ? undefined : json['payload'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function MessageDTOToJSON(json: any): MessageDTO {
    return MessageDTOToJSONTyped(json, false);
}

export function MessageDTOToJSONTyped(value?: MessageDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payload': value['payload'],
        'type': value['type'],
    };
}

