/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MosaicDTO } from './MosaicDTO';
import {
    MosaicDTOFromJSON,
    MosaicDTOFromJSONTyped,
    MosaicDTOToJSON,
    MosaicDTOToJSONTyped,
} from './MosaicDTO';

/**
 * 
 * @export
 * @interface MosaicListDTO
 */
export interface MosaicListDTO {
    /**
     * Array of mosaics
     * @type {Array<MosaicDTO>}
     * @memberof MosaicListDTO
     */
    data?: Array<MosaicDTO>;
}

/**
 * Check if a given object implements the MosaicListDTO interface.
 */
export function instanceOfMosaicListDTO(value: object): value is MosaicListDTO {
    return true;
}

export function MosaicListDTOFromJSON(json: any): MosaicListDTO {
    return MosaicListDTOFromJSONTyped(json, false);
}

export function MosaicListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicListDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MosaicDTOFromJSON)),
    };
}

export function MosaicListDTOToJSON(json: any): MosaicListDTO {
    return MosaicListDTOToJSONTyped(json, false);
}

export function MosaicListDTOToJSONTyped(value?: MosaicListDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MosaicDTOToJSON)),
    };
}

