/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MosaicIdDTO
 */
export interface MosaicIdDTO {
    /**
     * Namespace ID of the mosaic
     * @type {string}
     * @memberof MosaicIdDTO
     */
    namespaceId?: string;
    /**
     * Name of the mosaic
     * @type {string}
     * @memberof MosaicIdDTO
     */
    name?: string;
}

/**
 * Check if a given object implements the MosaicIdDTO interface.
 */
export function instanceOfMosaicIdDTO(value: object): value is MosaicIdDTO {
    return true;
}

export function MosaicIdDTOFromJSON(json: any): MosaicIdDTO {
    return MosaicIdDTOFromJSONTyped(json, false);
}

export function MosaicIdDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicIdDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'namespaceId': json['namespaceId'] == null ? undefined : json['namespaceId'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function MosaicIdDTOToJSON(json: any): MosaicIdDTO {
    return MosaicIdDTOToJSONTyped(json, false);
}

export function MosaicIdDTOToJSONTyped(value?: MosaicIdDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'namespaceId': value['namespaceId'],
        'name': value['name'],
    };
}

