/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MosaicIdDTO } from './MosaicIdDTO';
import {
    MosaicIdDTOFromJSON,
    MosaicIdDTOFromJSONTyped,
    MosaicIdDTOToJSON,
    MosaicIdDTOToJSONTyped,
} from './MosaicIdDTO';

/**
 * 
 * @export
 * @interface MosaicDTO
 */
export interface MosaicDTO {
    /**
     * Quantity of the mosaic
     * @type {number}
     * @memberof MosaicDTO
     */
    quantity?: number;
    /**
     * 
     * @type {MosaicIdDTO}
     * @memberof MosaicDTO
     */
    mosaicId?: MosaicIdDTO;
}

/**
 * Check if a given object implements the MosaicDTO interface.
 */
export function instanceOfMosaicDTO(value: object): value is MosaicDTO {
    return true;
}

export function MosaicDTOFromJSON(json: any): MosaicDTO {
    return MosaicDTOFromJSONTyped(json, false);
}

export function MosaicDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'mosaicId': json['mosaicId'] == null ? undefined : MosaicIdDTOFromJSON(json['mosaicId']),
    };
}

export function MosaicDTOToJSON(json: any): MosaicDTO {
    return MosaicDTOToJSONTyped(json, false);
}

export function MosaicDTOToJSONTyped(value?: MosaicDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
        'mosaicId': MosaicIdDTOToJSON(value['mosaicId']),
    };
}

