/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MosaicDefinitionListDTO
 */
export interface MosaicDefinitionListDTO {
    /**
     * Array of mosaic definitions
     * @type {Array<object>}
     * @memberof MosaicDefinitionListDTO
     */
    data?: Array<object>;
}

/**
 * Check if a given object implements the MosaicDefinitionListDTO interface.
 */
export function instanceOfMosaicDefinitionListDTO(value: object): value is MosaicDefinitionListDTO {
    return true;
}

export function MosaicDefinitionListDTOFromJSON(json: any): MosaicDefinitionListDTO {
    return MosaicDefinitionListDTOFromJSONTyped(json, false);
}

export function MosaicDefinitionListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MosaicDefinitionListDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function MosaicDefinitionListDTOToJSON(json: any): MosaicDefinitionListDTO {
    return MosaicDefinitionListDTOToJSONTyped(json, false);
}

export function MosaicDefinitionListDTOToJSONTyped(value?: MosaicDefinitionListDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

