/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NamespaceListDTO
 */
export interface NamespaceListDTO {
    /**
     * Array of namespaces
     * @type {Array<object>}
     * @memberof NamespaceListDTO
     */
    data?: Array<object>;
}

/**
 * Check if a given object implements the NamespaceListDTO interface.
 */
export function instanceOfNamespaceListDTO(value: object): value is NamespaceListDTO {
    return true;
}

export function NamespaceListDTOFromJSON(json: any): NamespaceListDTO {
    return NamespaceListDTOFromJSONTyped(json, false);
}

export function NamespaceListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamespaceListDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function NamespaceListDTOToJSON(json: any): NamespaceListDTO {
    return NamespaceListDTOToJSONTyped(json, false);
}

export function NamespaceListDTOToJSONTyped(value?: NamespaceListDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

