/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NisInfoDTO
 */
export interface NisInfoDTO {
    /**
     * Current NIS time
     * @type {number}
     * @memberof NisInfoDTO
     */
    currentTime?: number;
    /**
     * Application name
     * @type {string}
     * @memberof NisInfoDTO
     */
    application?: string;
    /**
     * NIS start time
     * @type {number}
     * @memberof NisInfoDTO
     */
    startTime?: number;
    /**
     * NIS version
     * @type {string}
     * @memberof NisInfoDTO
     */
    version?: string;
    /**
     * Signer public key
     * @type {string}
     * @memberof NisInfoDTO
     */
    signer?: string | null;
}

/**
 * Check if a given object implements the NisInfoDTO interface.
 */
export function instanceOfNisInfoDTO(value: object): value is NisInfoDTO {
    return true;
}

export function NisInfoDTOFromJSON(json: any): NisInfoDTO {
    return NisInfoDTOFromJSONTyped(json, false);
}

export function NisInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NisInfoDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'currentTime': json['currentTime'] == null ? undefined : json['currentTime'],
        'application': json['application'] == null ? undefined : json['application'],
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'version': json['version'] == null ? undefined : json['version'],
        'signer': json['signer'] == null ? undefined : json['signer'],
    };
}

export function NisInfoDTOToJSON(json: any): NisInfoDTO {
    return NisInfoDTOToJSONTyped(json, false);
}

export function NisInfoDTOToJSONTyped(value?: NisInfoDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentTime': value['currentTime'],
        'application': value['application'],
        'startTime': value['startTime'],
        'version': value['version'],
        'signer': value['signer'],
    };
}

