/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodeMetaDataDTO } from './NodeMetaDataDTO';
import {
    NodeMetaDataDTOFromJSON,
    NodeMetaDataDTOFromJSONTyped,
    NodeMetaDataDTOToJSON,
    NodeMetaDataDTOToJSONTyped,
} from './NodeMetaDataDTO';
import type { IdentityDTO } from './IdentityDTO';
import {
    IdentityDTOFromJSON,
    IdentityDTOFromJSONTyped,
    IdentityDTOToJSON,
    IdentityDTOToJSONTyped,
} from './IdentityDTO';
import type { EndpointDTO } from './EndpointDTO';
import {
    EndpointDTOFromJSON,
    EndpointDTOFromJSONTyped,
    EndpointDTOToJSON,
    EndpointDTOToJSONTyped,
} from './EndpointDTO';

/**
 * 
 * @export
 * @interface NodeDTO
 */
export interface NodeDTO {
    /**
     * 
     * @type {NodeMetaDataDTO}
     * @memberof NodeDTO
     */
    metaData?: NodeMetaDataDTO;
    /**
     * 
     * @type {EndpointDTO}
     * @memberof NodeDTO
     */
    endpoint?: EndpointDTO;
    /**
     * 
     * @type {IdentityDTO}
     * @memberof NodeDTO
     */
    identity?: IdentityDTO;
}

/**
 * Check if a given object implements the NodeDTO interface.
 */
export function instanceOfNodeDTO(value: object): value is NodeDTO {
    return true;
}

export function NodeDTOFromJSON(json: any): NodeDTO {
    return NodeDTOFromJSONTyped(json, false);
}

export function NodeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'metaData': json['metaData'] == null ? undefined : NodeMetaDataDTOFromJSON(json['metaData']),
        'endpoint': json['endpoint'] == null ? undefined : EndpointDTOFromJSON(json['endpoint']),
        'identity': json['identity'] == null ? undefined : IdentityDTOFromJSON(json['identity']),
    };
}

export function NodeDTOToJSON(json: any): NodeDTO {
    return NodeDTOToJSONTyped(json, false);
}

export function NodeDTOToJSONTyped(value?: NodeDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metaData': NodeMetaDataDTOToJSON(value['metaData']),
        'endpoint': EndpointDTOToJSON(value['endpoint']),
        'identity': IdentityDTOToJSON(value['identity']),
    };
}

