/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodeDTO } from './NodeDTO';
import {
    NodeDTOFromJSON,
    NodeDTOFromJSONTyped,
    NodeDTOToJSON,
    NodeDTOToJSONTyped,
} from './NodeDTO';

/**
 * 
 * @export
 * @interface NodeListDTO
 */
export interface NodeListDTO {
    /**
     * Array of nodes
     * @type {Array<NodeDTO>}
     * @memberof NodeListDTO
     */
    data?: Array<NodeDTO>;
}

/**
 * Check if a given object implements the NodeListDTO interface.
 */
export function instanceOfNodeListDTO(value: object): value is NodeListDTO {
    return true;
}

export function NodeListDTOFromJSON(json: any): NodeListDTO {
    return NodeListDTOFromJSONTyped(json, false);
}

export function NodeListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeListDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(NodeDTOFromJSON)),
    };
}

export function NodeListDTOToJSON(json: any): NodeListDTO {
    return NodeListDTOToJSONTyped(json, false);
}

export function NodeListDTOToJSONTyped(value?: NodeListDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(NodeDTOToJSON)),
    };
}

