/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeMetaDataDTO
 */
export interface NodeMetaDataDTO {
    /**
     * Node features
     * @type {number}
     * @memberof NodeMetaDataDTO
     */
    features?: number;
    /**
     * Application name
     * @type {string}
     * @memberof NodeMetaDataDTO
     */
    application?: string | null;
    /**
     * Network ID
     * @type {number}
     * @memberof NodeMetaDataDTO
     */
    networkId?: number;
    /**
     * Node version
     * @type {string}
     * @memberof NodeMetaDataDTO
     */
    version?: string;
    /**
     * Platform information
     * @type {string}
     * @memberof NodeMetaDataDTO
     */
    platform?: string;
}

/**
 * Check if a given object implements the NodeMetaDataDTO interface.
 */
export function instanceOfNodeMetaDataDTO(value: object): value is NodeMetaDataDTO {
    return true;
}

export function NodeMetaDataDTOFromJSON(json: any): NodeMetaDataDTO {
    return NodeMetaDataDTOFromJSONTyped(json, false);
}

export function NodeMetaDataDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeMetaDataDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'features': json['features'] == null ? undefined : json['features'],
        'application': json['application'] == null ? undefined : json['application'],
        'networkId': json['networkId'] == null ? undefined : json['networkId'],
        'version': json['version'] == null ? undefined : json['version'],
        'platform': json['platform'] == null ? undefined : json['platform'],
    };
}

export function NodeMetaDataDTOToJSON(json: any): NodeMetaDataDTO {
    return NodeMetaDataDTOToJSONTyped(json, false);
}

export function NodeMetaDataDTOToJSONTyped(value?: NodeMetaDataDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'features': value['features'],
        'application': value['application'],
        'networkId': value['networkId'],
        'version': value['version'],
        'platform': value['platform'],
    };
}

