/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSynchronizationDTO
 */
export interface TimeSynchronizationDTO {
    /**
     * Date and time
     * @type {string}
     * @memberof TimeSynchronizationDTO
     */
    dateTime?: string;
    /**
     * Current time offset
     * @type {number}
     * @memberof TimeSynchronizationDTO
     */
    currentTimeOffset?: number;
    /**
     * Change in time offset
     * @type {number}
     * @memberof TimeSynchronizationDTO
     */
    change?: number;
}

/**
 * Check if a given object implements the TimeSynchronizationDTO interface.
 */
export function instanceOfTimeSynchronizationDTO(value: object): value is TimeSynchronizationDTO {
    return true;
}

export function TimeSynchronizationDTOFromJSON(json: any): TimeSynchronizationDTO {
    return TimeSynchronizationDTOFromJSONTyped(json, false);
}

export function TimeSynchronizationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSynchronizationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'dateTime': json['dateTime'] == null ? undefined : json['dateTime'],
        'currentTimeOffset': json['currentTimeOffset'] == null ? undefined : json['currentTimeOffset'],
        'change': json['change'] == null ? undefined : json['change'],
    };
}

export function TimeSynchronizationDTOToJSON(json: any): TimeSynchronizationDTO {
    return TimeSynchronizationDTOToJSONTyped(json, false);
}

export function TimeSynchronizationDTOToJSONTyped(value?: TimeSynchronizationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dateTime': value['dateTime'],
        'currentTimeOffset': value['currentTimeOffset'],
        'change': value['change'],
    };
}

