/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeSynchronizationDTO } from './TimeSynchronizationDTO';
import {
    TimeSynchronizationDTOFromJSON,
    TimeSynchronizationDTOFromJSONTyped,
    TimeSynchronizationDTOToJSON,
    TimeSynchronizationDTOToJSONTyped,
} from './TimeSynchronizationDTO';

/**
 * 
 * @export
 * @interface TimeSynchronizationListDTO
 */
export interface TimeSynchronizationListDTO {
    /**
     * Array of time synchronization data
     * @type {Array<TimeSynchronizationDTO>}
     * @memberof TimeSynchronizationListDTO
     */
    data?: Array<TimeSynchronizationDTO>;
}

/**
 * Check if a given object implements the TimeSynchronizationListDTO interface.
 */
export function instanceOfTimeSynchronizationListDTO(value: object): value is TimeSynchronizationListDTO {
    return true;
}

export function TimeSynchronizationListDTOFromJSON(json: any): TimeSynchronizationListDTO {
    return TimeSynchronizationListDTOFromJSONTyped(json, false);
}

export function TimeSynchronizationListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSynchronizationListDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TimeSynchronizationDTOFromJSON)),
    };
}

export function TimeSynchronizationListDTOToJSON(json: any): TimeSynchronizationListDTO {
    return TimeSynchronizationListDTOToJSONTyped(json, false);
}

export function TimeSynchronizationListDTOToJSONTyped(value?: TimeSynchronizationListDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TimeSynchronizationDTOToJSON)),
    };
}

