/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionMetaDataPairDTO } from './TransactionMetaDataPairDTO';
import {
    TransactionMetaDataPairDTOFromJSON,
    TransactionMetaDataPairDTOFromJSONTyped,
    TransactionMetaDataPairDTOToJSON,
    TransactionMetaDataPairDTOToJSONTyped,
} from './TransactionMetaDataPairDTO';

/**
 * 
 * @export
 * @interface TransactionListDTO
 */
export interface TransactionListDTO {
    /**
     * Array of transaction metadata pairs
     * @type {Array<TransactionMetaDataPairDTO>}
     * @memberof TransactionListDTO
     */
    data?: Array<TransactionMetaDataPairDTO>;
}

/**
 * Check if a given object implements the TransactionListDTO interface.
 */
export function instanceOfTransactionListDTO(value: object): value is TransactionListDTO {
    return true;
}

export function TransactionListDTOFromJSON(json: any): TransactionListDTO {
    return TransactionListDTOFromJSONTyped(json, false);
}

export function TransactionListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionListDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TransactionMetaDataPairDTOFromJSON)),
    };
}

export function TransactionListDTOToJSON(json: any): TransactionListDTO {
    return TransactionListDTOToJSONTyped(json, false);
}

export function TransactionListDTOToJSONTyped(value?: TransactionListDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TransactionMetaDataPairDTOToJSON)),
    };
}

