/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDTO } from './MessageDTO';
import {
    MessageDTOFromJSON,
    MessageDTOFromJSONTyped,
    MessageDTOToJSON,
    MessageDTOToJSONTyped,
} from './MessageDTO';

/**
 * 
 * @export
 * @interface TransactionDTO
 */
export interface TransactionDTO {
    /**
     * Transaction timestamp
     * @type {number}
     * @memberof TransactionDTO
     */
    timeStamp?: number;
    /**
     * Transaction amount in micro XEM
     * @type {number}
     * @memberof TransactionDTO
     */
    amount?: number;
    /**
     * Transaction signature
     * @type {string}
     * @memberof TransactionDTO
     */
    signature?: string;
    /**
     * Transaction fee in micro XEM
     * @type {number}
     * @memberof TransactionDTO
     */
    fee?: number;
    /**
     * Recipient address
     * @type {string}
     * @memberof TransactionDTO
     */
    recipient?: string;
    /**
     * Transaction type
     * @type {number}
     * @memberof TransactionDTO
     */
    type?: number;
    /**
     * Transaction deadline
     * @type {number}
     * @memberof TransactionDTO
     */
    deadline?: number;
    /**
     * 
     * @type {MessageDTO}
     * @memberof TransactionDTO
     */
    message?: MessageDTO;
    /**
     * Transaction version
     * @type {number}
     * @memberof TransactionDTO
     */
    version?: number;
    /**
     * Public key of the transaction signer
     * @type {string}
     * @memberof TransactionDTO
     */
    signer?: string;
}

/**
 * Check if a given object implements the TransactionDTO interface.
 */
export function instanceOfTransactionDTO(value: object): value is TransactionDTO {
    return true;
}

export function TransactionDTOFromJSON(json: any): TransactionDTO {
    return TransactionDTOFromJSONTyped(json, false);
}

export function TransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'timeStamp': json['timeStamp'] == null ? undefined : json['timeStamp'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'signature': json['signature'] == null ? undefined : json['signature'],
        'fee': json['fee'] == null ? undefined : json['fee'],
        'recipient': json['recipient'] == null ? undefined : json['recipient'],
        'type': json['type'] == null ? undefined : json['type'],
        'deadline': json['deadline'] == null ? undefined : json['deadline'],
        'message': json['message'] == null ? undefined : MessageDTOFromJSON(json['message']),
        'version': json['version'] == null ? undefined : json['version'],
        'signer': json['signer'] == null ? undefined : json['signer'],
    };
}

export function TransactionDTOToJSON(json: any): TransactionDTO {
    return TransactionDTOToJSONTyped(json, false);
}

export function TransactionDTOToJSONTyped(value?: TransactionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeStamp': value['timeStamp'],
        'amount': value['amount'],
        'signature': value['signature'],
        'fee': value['fee'],
        'recipient': value['recipient'],
        'type': value['type'],
        'deadline': value['deadline'],
        'message': MessageDTOToJSON(value['message']),
        'version': value['version'],
        'signer': value['signer'],
    };
}

