/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionDTO } from './TransactionDTO';
import {
    TransactionDTOFromJSON,
    TransactionDTOFromJSONTyped,
    TransactionDTOToJSON,
    TransactionDTOToJSONTyped,
} from './TransactionDTO';
import type { TransactionMetaDTO } from './TransactionMetaDTO';
import {
    TransactionMetaDTOFromJSON,
    TransactionMetaDTOFromJSONTyped,
    TransactionMetaDTOToJSON,
    TransactionMetaDTOToJSONTyped,
} from './TransactionMetaDTO';

/**
 * 
 * @export
 * @interface TransactionMetaDataPairDTO
 */
export interface TransactionMetaDataPairDTO {
    /**
     * 
     * @type {TransactionMetaDTO}
     * @memberof TransactionMetaDataPairDTO
     */
    meta?: TransactionMetaDTO;
    /**
     * 
     * @type {TransactionDTO}
     * @memberof TransactionMetaDataPairDTO
     */
    transaction?: TransactionDTO;
}

/**
 * Check if a given object implements the TransactionMetaDataPairDTO interface.
 */
export function instanceOfTransactionMetaDataPairDTO(value: object): value is TransactionMetaDataPairDTO {
    return true;
}

export function TransactionMetaDataPairDTOFromJSON(json: any): TransactionMetaDataPairDTO {
    return TransactionMetaDataPairDTOFromJSONTyped(json, false);
}

export function TransactionMetaDataPairDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionMetaDataPairDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : TransactionMetaDTOFromJSON(json['meta']),
        'transaction': json['transaction'] == null ? undefined : TransactionDTOFromJSON(json['transaction']),
    };
}

export function TransactionMetaDataPairDTOToJSON(json: any): TransactionMetaDataPairDTO {
    return TransactionMetaDataPairDTOToJSONTyped(json, false);
}

export function TransactionMetaDataPairDTOToJSONTyped(value?: TransactionMetaDataPairDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': TransactionMetaDTOToJSON(value['meta']),
        'transaction': TransactionDTOToJSON(value['transaction']),
    };
}

