/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HashDTO } from './HashDTO';
import {
    HashDTOFromJSON,
    HashDTOFromJSONTyped,
    HashDTOToJSON,
    HashDTOToJSONTyped,
} from './HashDTO';

/**
 * 
 * @export
 * @interface TransactionMetaDTO
 */
export interface TransactionMetaDTO {
    /**
     * Inner transaction hash (for multisig transactions)
     * @type {object}
     * @memberof TransactionMetaDTO
     */
    innerHash?: object;
    /**
     * Transaction database ID
     * @type {number}
     * @memberof TransactionMetaDTO
     */
    id?: number;
    /**
     * 
     * @type {HashDTO}
     * @memberof TransactionMetaDTO
     */
    hash?: HashDTO;
    /**
     * Block height of the transaction
     * @type {number}
     * @memberof TransactionMetaDTO
     */
    height?: number;
}

/**
 * Check if a given object implements the TransactionMetaDTO interface.
 */
export function instanceOfTransactionMetaDTO(value: object): value is TransactionMetaDTO {
    return true;
}

export function TransactionMetaDTOFromJSON(json: any): TransactionMetaDTO {
    return TransactionMetaDTOFromJSONTyped(json, false);
}

export function TransactionMetaDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionMetaDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'innerHash': json['innerHash'] == null ? undefined : json['innerHash'],
        'id': json['id'] == null ? undefined : json['id'],
        'hash': json['hash'] == null ? undefined : HashDTOFromJSON(json['hash']),
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function TransactionMetaDTOToJSON(json: any): TransactionMetaDTO {
    return TransactionMetaDTOToJSONTyped(json, false);
}

export function TransactionMetaDTOToJSONTyped(value?: TransactionMetaDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'innerHash': value['innerHash'],
        'id': value['id'],
        'hash': HashDTOToJSON(value['hash']),
        'height': value['height'],
    };
}

