/* tslint:disable */
/* eslint-disable */
/**
 * NEM NIS API
 * Version 1.19  19:27, March 20, 2017  [https://nemproject.github.io/](https://nemproject.github.io/)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnconfirmedTransactionListDTO
 */
export interface UnconfirmedTransactionListDTO {
    /**
     * Array of unconfirmed transactions
     * @type {Array<object>}
     * @memberof UnconfirmedTransactionListDTO
     */
    data?: Array<object>;
}

/**
 * Check if a given object implements the UnconfirmedTransactionListDTO interface.
 */
export function instanceOfUnconfirmedTransactionListDTO(value: object): value is UnconfirmedTransactionListDTO {
    return true;
}

export function UnconfirmedTransactionListDTOFromJSON(json: any): UnconfirmedTransactionListDTO {
    return UnconfirmedTransactionListDTOFromJSONTyped(json, false);
}

export function UnconfirmedTransactionListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnconfirmedTransactionListDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function UnconfirmedTransactionListDTOToJSON(json: any): UnconfirmedTransactionListDTO {
    return UnconfirmedTransactionListDTOToJSONTyped(json, false);
}

export function UnconfirmedTransactionListDTOToJSONTyped(value?: UnconfirmedTransactionListDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

